### ISSUE TITLE
Need to write test cases for utilities

### ISSUE THREAD

**Issue by neodisk17** [neodisk17/vscode-ext-flutter-color-viewer#40]
Needed to write test cases for the utilites which are present in the src/utils folder

**Comment by AdityaDhavale** [comment]
@neodisk17 I would like to work on this issue , will u please assign me?

**Comment by neodisk17** [comment]
Sure
Happy Hactoberfest

**Comment by AdityaDhavale** [comment]
@neodisk17 could u please explain , like what do u exactly mean by writing testcases

**Comment by AdityaDhavale** [comment]
@neodisk17 I've written test cases for the utilities in src/utils folder . Please check and kindly merge my PR

**Comment by neodisk17** [comment]
@AdityaDhavale 
I have added some comments in the PR, pls have a check and add a comment if you are working on it.

If you are not replying within 2-3 days, I will close the PR and assign the issue to someone else

**Comment by AdityaDhavale** [comment]
@neodisk17 
Going through some issues lately, you can unassign me and assign someone else :)
Thank you for giving me the opportunity to work on the issue .

**Comment by neodisk17** [comment]
Okay, un-assigning the issue so that other's would also get chance
