### ISSUE TITLE
QML use ARGB  Color

### ISSUE THREAD

**Issue by CMLNT** [neodisk17/vscode-ext-flutter-color-viewer#45]
<img width="207" alt="image" src="https://github.com/neodisk17/vscode-ext-flutter-color-viewer/assets/13372840/0b97dafd-3d62-48d0-a846-ec8fbd6fcb1c">

QML files use ARGB colors with alpha in front of RGB
The alpha of the plug-in is RGBA at the end of RGB
Can QML be differentiated using ARGB patterns

**Comment by neodisk17** [comment]
Hi @CMLNT 
Sure will check this

Sorry for the late reply, was occupied with other stuff
