### ISSUE TITLE
[BUG}: Doesn't show shortcut for default colors

### ISSUE THREAD

**Issue by Fevzettin1** [neodisk17/vscode-ext-flutter-color-viewer#64]
I want the color boxes to show as before for the default colors. How can I do this?

![image](https://github.com/user-attachments/assets/f15aff3a-6422-4a26-b413-0d8f2d524633)

Is it possible to have the bottom color boxes in the default colors above?

**Comment by neodisk17** [comment]
Hi @Fevzettin1,
Can you provide me more details about the issue

As I am able to see the color box for the default colours

<img width="357" alt="image" src="https://github.com/user-attachments/assets/861c364e-af5c-465a-93c7-833f17481ebc">


<img width="407" alt="image" src="https://github.com/user-attachments/assets/aeb9d689-50e6-4f19-a20e-5e323d1c3043">


It would be helpful if you can share the vs code version, plugin version and a sample file to test at my end

**Comment by Fevzettin1** [comment]
Hi @neodisk17 , first of all, thank you for trying to help.

VS Code Ver. 1.94.0 (user setup)

flutter doctor:
[√] Flutter (Channel beta, 3.26.0-0.1.pre, on Microsoft Windows [Version 10.0.27718.1000], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.12.0 Preview 2.1)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.94.0)
...

VS Code Extensions Versions:
Flutter Color v2.0.0
Dart v3.98.0
Flutter v3.98.0

![image](https://github.com/user-attachments/assets/2f0eee2f-0f5e-4762-a48c-e2fa943f3156)

import 'package:flutter/material.dart';

class ColorList {
  static const Color primary = contentColorCyan;
  static const Color menuBackground = Color(0xFF090912);
  static const Color itemsBackground = Color(0xFF1B2339);
  static const Color pageBackground = Color(0xFF282E45);
  static const Color mainTextColor1 = Colors.white;
  static const Color mainTextColor2 = Colors.white70;
  static const Color mainTextColor3 = Colors.white38;
  static const Color mainGridLineColor = Colors.white10;
  static const Color borderColor = Colors.white54;
  static const Color gridLinesColor = Color(0x11FFFFFF);

  static const Color contentColorBlack = Colors.black;
  static const Color contentColorWhite = Colors.white;
  static const Color contentColorBlue = Color(0xFF2196F3);
  static const Color contentColorYellow = Color(0xFFFFC300);
  static const Color contentColorOrange = Color(0xFFFF683B);
  static const Color contentColorGreen = Color(0xFF3BFF49);
  static const Color contentColorPurple = Color(0xFF6E1BFF);
  static const Color contentColorPink = Color(0xFFFF3AF2);
  static const Color contentColorRed = Color(0xFFE80054);
  static const Color contentColorCyan = Color(0xFF50E4FF);
}

I hope these are enough

**Comment by neodisk17** [comment]
Hi @Fevzettin1 
I have checked the data that you have provided, It's working in my system.
My flutter version is 3.22.0. - Stable Channel

<img width="656" alt="image" src="https://github.com/user-attachments/assets/37a1c8a8-f20c-4139-8dc8-eb256a45f6d7">


I am thinking it might be something with the flutter beta version.
I will check it once on beta version as well and let you know

**Comment by neodisk17** [comment]
Hi @Fevzettin1 ,
I have checked the beta version as well. It's working fine at my end.
If you can provide me a way to reproduce it, maybe I can check and get back on it. 
Until then I am closing this issue. Feel Free to open the issue again once you get any re-producible way
